<a href="https://colab.research.google.com/github/mehdihosseinimoghadam/Pytorch-Tutorial/blob/main/Tensor_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import torch
import numpy as np

In [3]:
a1 = torch.empty(1) d     # One Dimentional Tensor   
a2 = torch.empty(2,2)     # Two Dimentional Tensor
a3 = torch.empty(2,2,2)   # Three Dimentional Tensor
print(a1)
print(a2)
print(a3)

tensor([-4.5370e+09])
tensor([[-4.5370e+09,  3.0649e-41],
        [ 4.4842e-44,  0.0000e+00]])
tensor([[[-4.5370e+09,  3.0649e-41],
         [ 0.0000e+00,  1.5898e-05]],

        [[ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00]]])


In [5]:
a = torch.zeros(2,2)
b = torch.ones(2,2)
c = torch.rand(2,2)

print(a)
print(b)
print(c)

tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.3240, 0.5207],
        [0.3225, 0.4818]])


In [9]:
a = torch.rand(2,2)
b = torch.rand(2, 2, dtype=torch.float32) # Changing data type

print(a)
a.add_(b) # In Place Operation
print(a) 

tensor([[0.5101, 0.8474],
        [0.1926, 0.2485]])
tensor([[0.9874, 1.5617],
        [1.1149, 0.2610]])


In [12]:
a = torch.rand(2,3,4)
b = a.view(3,8)
c = a.view(-1,2)

print(f'Size of a is {a.size()}, Size of b is {b.size()}, and Size of c is {c.size()}')

Size of a is torch.Size([2, 3, 4]), Size of b is torch.Size([3, 8]), and Size of c is torch.Size([12, 2])


In [13]:
a = torch.rand(2,2)
b = a.numpy()

print(type(a), type(b))

<class 'torch.Tensor'> <class 'numpy.ndarray'>


In [14]:
a = torch.ones(2)
b = a.numpy()

a.add_(2)

print(a,b)

tensor([3., 3.]) [3. 3.]


In [17]:
a = np.ones(2)
b = torch.from_numpy(a)

print(a,b)

[1. 1.] tensor([1., 1.], dtype=torch.float64)


In [20]:
a = 2 * torch.ones(2)
b = 3 * torch.ones(2)

c = a * b
d = a - b
e = a + b

print(c,d,e)

tensor([6., 6.]) tensor([-1., -1.]) tensor([5., 5.])


In [24]:
if torch.cuda.is_available():
  device = torch.device('cuda')
  a = torch.rand(2, device=device)
  b = torch.rand(2, device=device)


print(a*b)

tensor([0.2784, 1.2305])
tensor([12., 12.])
