<a href="https://colab.research.google.com/github/mehdihosseinimoghadam/Pytorch-Tutorial/blob/main/Tensor_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np

In [3]:
a1 = torch.empty(1) d     # One Dimentional Tensor   
a2 = torch.empty(2,2)     # Two Dimentional Tensor
a3 = torch.empty(2,2,2)   # Three Dimentional Tensor
print(a1)
print(a2)
print(a3)

tensor([-4.5370e+09])
tensor([[-4.5370e+09,  3.0649e-41],
        [ 4.4842e-44,  0.0000e+00]])
tensor([[[-4.5370e+09,  3.0649e-41],
         [ 0.0000e+00,  1.5898e-05]],

        [[ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00]]])


In [5]:
a = torch.zeros(2,2)
b = torch.ones(2,2)
c = torch.rand(2,2)

print(a)
print(b)
print(c)

tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.3240, 0.5207],
        [0.3225, 0.4818]])


In [9]:
a = torch.rand(2,2)
b = torch.rand(2, 2, dtype=torch.float32) # Changing data type

print(a)
a.add_(b) # In Place Operation
print(a) 

tensor([[0.5101, 0.8474],
        [0.1926, 0.2485]])
tensor([[0.9874, 1.5617],
        [1.1149, 0.2610]])


In [12]:
a = torch.rand(2,3,4)
b = a.view(3,8)
c = a.view(-1,2)

print(f'Size of a is {a.size()}, Size of b is {b.size()}, and Size of c is {c.size()}')

Size of a is torch.Size([2, 3, 4]), Size of b is torch.Size([3, 8]), and Size of c is torch.Size([12, 2])


In [13]:
a = torch.rand(2,2)
b = a.numpy()

print(type(a), type(b))

<class 'torch.Tensor'> <class 'numpy.ndarray'>


In [14]:
a = torch.ones(2)
b = a.numpy()

a.add_(2)

print(a,b)

tensor([3., 3.]) [3. 3.]


In [17]:
a = np.ones(2)
b = torch.from_numpy(a)

print(a,b)

[1. 1.] tensor([1., 1.], dtype=torch.float64)


In [20]:
a = 2 * torch.ones(2)
b = 3 * torch.ones(2)

c = a * b
d = a - b
e = a + b

print(c,d,e)

tensor([6., 6.]) tensor([-1., -1.]) tensor([5., 5.])


In [24]:
if torch.cuda.is_available():
  device = torch.device('cuda')
  a = torch.rand(2, device=device)
  b = torch.rand(2, device=device)


print(a*b)

tensor([0.2784, 1.2305])
tensor([12., 12.])


In [21]:
x0 = torch.rand(1,2,4,1,1)
x = torch.rand(2,4)
print(x)
y = torch.rand(2,3)
print(x.size())                             # return tuple-like object of dimensions
z = torch.cat([x, y], dim=1)                # concatenates tensors along dim
print(z.size())
y = x.transpose(0,1)                        # swaps dimensions a and b
print(y.size())                             
y = x.unsqueeze(0)                        # tensor with added axis
print(y.size())   
y = x.unsqueeze(1)                        # tensor with added axis
print(y.size()) 
print(x0.size())
y0 = x0.squeeze()                             # removes all dimensions of size 1 (a,1,b,1) -> (a,b)
print(y0.size())
y0 = x0.squeeze(dim=3)                      # removes specified dimension of size 1 (a,1,b,1) -> (a,b,1)
print(y0.size())

tensor([[0.0045, 0.9892, 0.1221, 0.4307],
        [0.1999, 0.3799, 0.0320, 0.5065]])
torch.Size([2, 4])
torch.Size([2, 7])
torch.Size([4, 2])
torch.Size([1, 2, 4])
torch.Size([2, 1, 4])
torch.Size([1, 2, 4, 1, 1])
torch.Size([2, 4])
torch.Size([1, 2, 4, 1])


In [8]:
a = torch.tensor([1,3,4],dtype=torch.float32, requires_grad=True)
a.unbind()

(tensor(1., grad_fn=<UnbindBackward0>),
 tensor(3., grad_fn=<UnbindBackward0>),
 tensor(4., grad_fn=<UnbindBackward0>))

In [3]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

device

device(type='cuda')

In [4]:
x = torch.rand(1,3)
x = x.to(device=device)
x

tensor([[0.2378, 0.5189, 0.2909]], device='cuda:0')